In [1]:
import pandas as pd
from tqdm import tqdm

In [2]:
new_business_df = pd.read_csv(r"cleaned_data/splited_data/train/new_business.csv")
new_business_df

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,0,Si6LXSR9gvAbmgO5DzV2cw,Lafitte's Landing Seafood House,1700 Lapalco Blvd,Harvey,LA,70058.0,29.875482,-90.049380,2.5,38,0,"{'WiFi': ""'no'"", 'RestaurantsReservations': 'T...","Restaurants, Soup, Seafood, Burgers","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
1,3,FRYkg_JvsWU9xIXZsEZcVA,Altamura,2127 Prytania St,New Orleans,LA,70115.0,29.933388,-90.079498,3.5,27,0,"{'Alcohol': ""'full_bar'"", 'OutdoorSeating': 'T...","Cocktail Bars, Italian, Nightlife, Seafood, Ba...","{'Monday': '17:0-22:0', 'Wednesday': '17:0-22:..."
2,4,LGqiubTmpJ-A1L5n7dmc6g,Domino's Pizza,"1525 Lapalco Blvd, # A",Harvey,LA,70058.0,29.875320,-90.045817,1.5,14,0,"{'RestaurantsGoodForGroups': 'False', 'Caters'...","Restaurants, Sandwiches, Pizza, Chicken Wings","{'Monday': '10:0-1:0', 'Tuesday': '10:0-1:0', ..."
3,5,4IcB3QyMEA85UTWFKh9O9A,Eat Mah Taco @ Pal's Lounge,949 N Rendon St,New Orleans,LA,70119.0,29.976762,-90.086423,4.5,8,0,"{'RestaurantsPriceRange2': '1', 'RestaurantsAt...","American (New), Food, Bars, Nightlife, Lounges...",{'Tuesday': '17:0-22:0'}
4,6,Edg22x3CZkIv0GUib2oEFA,Mellow Mushroom,8227 Oak St,New Orleans,LA,70118.0,29.948624,-90.131250,3.5,149,0,"{'RestaurantsTakeOut': 'True', 'GoodForKids': ...","Pizza, Restaurants, Bars, Nightlife, Sandwiches","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3530,4442,H6CjgNyCnbkcEB-ZaKufdw,CVS Pharmacy,1401 Veterans Blvd,Metairie,LA,70005.0,30.002400,-90.138324,2.0,11,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Drugstores, Pharmacy, Health & Medical, Conven...","{'Monday': '8:0-22:0', 'Tuesday': '10:0-20:0',..."
3531,4443,2OcVR4GRcmVsC118dn2QWA,Jackson Brewery,600 Decatur St,New Orleans,LA,70130.0,29.955925,-90.062962,2.5,41,1,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Bars, Restaurants, Nightlife, Shopping Centers...","{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'..."
3532,4444,E-Mq9XSHtu4n85SXlV-AAA,McAlister's Deli,"1000 W Esplanade, Ste A13",Kenner,LA,70065.0,30.021139,-90.251166,3.0,39,1,"{'Alcohol': ""u'none'"", 'GoodForKids': 'True', ...","Delis, Sandwiches, Salad, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '10:30-16:0',..."
3533,4445,PBbhDFJdUS7ebuRa1ggjaQ,Cafe Gentilly,5339 Franklin Ave,New Orleans,LA,70122.0,30.013081,-90.050785,4.5,100,0,"{'WiFi': ""'no'"", 'OutdoorSeating': 'False', 'A...","Seafood, Restaurants, Burgers, Cajun/Creole, B...","{'Monday': '7:0-19:0', 'Tuesday': '7:0-19:0', ..."
3534,4446,_eafo0pYcxOvziwR4JXj_Q,CreAsian,930 Canal St,New Orleans,LA,70112.0,29.954709,-90.071746,3.0,54,0,"{'BusinessAcceptsCreditCards': 'True', 'Alcoho...","Vietnamese, Restaurants, Chinese, Asian Fusion",NaN

In [4]:
(new_business_df["business_id"].isna()).sum()

0

In [5]:
new_user_df = pd.read_csv(r"cleaned_data/splited_data/train/new_user.csv")
new_user_df

,Unnamed: 0,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,0,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","['ueRPE0CX75ePGMqOFVj6IQ', 'kuDmRGcvJhFCHEXTNH...",...,264,184,157,251,1847,7054,3131,3131,1521,1946
1,1,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","['enx1vVPnfdNUdPho6PH_wg', '1OocYCAZixwbAXueW7...",...,4,1,6,2,12,16,26,26,10,9
2,3,SgiBkhXeqIKl1PlFpZOycQ,Eugene,682,2006-08-25 16:47:25,1819,1138,1297,"2007,2008,2009,2010,2011","['PutMYRE0vSv3vDQ2LnURqA', 'gfR80SvOyWL45S8vPM...",...,17,17,22,34,67,158,221,221,45,17
3,4,fJZO_skqpnhk1kvomI4dmA,Jennifer,25,2008-07-14 16:01:36,29,2,19,NaN,"['EMJV9rib660I4RpMsbzWbg', 'GJv1yf_IhUZqpDjFr8...",...,1,0,0,0,6,2,2,2,1,0
4,5,1L3O2CUTk27SnmqyPBWQdQ,Helen,38,2010-09-09 16:41:46,62,6,9,NaN,"['vJMUItkTvppKlJYW0DCu_A', 'Lw1BNeWfe5aQEFiI2r...",...,0,0,2,0,1,2,0,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16344,191927,3hCi5lRg_9hQOBlYAUe3Yg,Daniel,10,2016-05-18 02:30:18,1,2,0,NaN,[],...,0,0,0,0,0,0,0,0,0,0
16345,193720,dP1Twn9iMAtbw0Gncf9ozg,Jeff,44,2011-01-07 04:42:36,23,5,4,NaN,[],...,0,0,0,0,0,0,0,0,0,0
16346,194152,Ztmck964ywp2FrikpbfPOg,K,50,2011-03-12 22:53:57,27,5,7,NaN,[],...,0,0,0,0,0,0,0,0,0,0
16347,195106,wk6JhfgmX015JQcc3Uqw_A,Mike,55,2009-02-19 14:38:53,104,26,30,2010,"['7nlkiPQKHeYxzgA9BvXlbg', 'pnTiEaqM4slogpY97n...",...,0,0,0,0,2,3,3,3,2,1
16348,197487,wnZghGglaUJttE5r2D7vkg,Brigitte,13,2014-12-30 00:35:04,10,0,3,NaN,"['1yNQMVfjHB4JzyOLzrtldQ', '3LwwMCrXttFOR3P0g6...",...,0,0,0,0,0,0,0,0,0,0

In [6]:
import json

f = open("cleaned_data/splited_data/train/review_train.json")
data = json.load(f)
review_train_df = pd.DataFrame(data["data"], columns=data["columns"])
review_train_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,compliment_count,count
0,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1.0,0.0,1.0,Cute interior and owner (?) gave us tour of up...,1.484427e+09,NaN,None
1,jC-fGfx-YLqxVBcyTAd4Pw,EBa-0-6AKoy6jziNexDJtg,W4ZEKkva9HpAdZG88juwyQ,3.0,0.0,0.0,0.0,"In a word... ""OVERRATED!"". The food took fore...",1.388285e+09,NaN,None
2,Ki90-hauSIfW_7sBuBBqfA,Z2cOL3n9V8NoguJ-uU_Nvw,j8JOZvfeHEfUWq3gEz6ABQ,2.0,2.0,3.0,0.0,NEVER AGAIN. This is a so called restaurant th...,1.402499e+09,NaN,None
3,fGYcFOHfQL4stYPdD3J47g,CgyCtH9CbLO7J_uO3cL7OA,PzhPMkaNYiKDTHoTG0r8rw,4.0,0.0,0.0,0.0,After 3 weeks of working in the area I finally...,1.474239e+09,NaN,None
4,zRIH5eDA2GbynjZPrk8dDg,07aVWNhBhpwqW3MdqoKDKQ,jLerIZFpe25jOUf722qzBA,3.0,1.0,0.0,1.0,My food only merited maybe two stars but I wil...,1.300625e+09,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...
189568,None,pmicanKB33RORORyuW-FRw,ujYhU3bX35BCVj1NUbSQpQ,NaN,NaN,NaN,NaN,Not a huge menu...some sandwiches and pastries...,1.372874e+09,0.0,None
189569,None,6mqnjHUgNEGtb9H5dxQZew,TcNZXteosegb1RO4O5hREw,NaN,NaN,NaN,NaN,Fried Oyster Poorboys on Monday and Wednesday!...,1.405354e+09,0.0,None
189570,None,S7bRCe31-pZNNivo9HmYeg,95tAFc8hVfzVr0uRJuDbaw,NaN,NaN,NaN,NaN,Not 24hr!!!!,1.429599e+09,0.0,None
189571,None,S7bRCe31-pZNNivo9HmYeg,0ZeGH15LV98FuijA1XrWoA,NaN,NaN,NaN,NaN,Kyoto is closed for good. Some corporation bou...,1.476826e+09,0.0,None
189572,None,ZoTe31b0sQ2EH-ucMuxyvw,mbKGY9CcbjSvy3Iyumeg3Q,NaN,NaN,NaN,NaN,"Great food, even better margaritas!!! Best Mex...",1.460166e+09,0.0,None

In [7]:
check_in_df = pd.read_csv(r"cleaned_data/splited_data/train/new_check_in.csv")
check_in_df

,Unnamed: 0,business_id,date
0,0,--8IbOsAAxjKRoYsBFL-PA,"2015-06-06 01:03:19, 2015-07-29 16:50:58, 2015..."
1,2,-0__F9fnKt8uioCKztF5Ww,"2016-06-22 17:23:34, 2016-06-30 00:49:09, 2016..."
2,3,-0ltw8--HLuulPyOSspqAQ,"2010-08-29 02:16:22, 2012-04-09 02:42:28, 2012..."
3,4,-1XSzguS6XLN-V6MVZMg2A,"2015-12-12 02:42:54, 2015-12-22 03:13:48, 2015..."
4,5,-4x3pVUUsfWmKEilWKsOZQ,"2014-04-27 17:56:21, 2014-05-06 17:37:10, 2014..."
...,...,...,...
3530,4442,zurZgdE3W9jJnU6VAgTdSg,"2013-06-12 15:13:35, 2013-06-25 13:21:06, 2013..."
3531,4443,zvGNZF827KyzLupKiG4Xtw,"2010-05-09 12:38:46, 2010-05-15 11:21:35, 2010..."
3532,4444,zwe9H6Xxqb1_E09A20Ptgg,"2011-03-27 22:47:17, 2011-03-28 15:10:21, 2011..."
3533,4446,zzbZtgPYZS8sTIWQH6DwEw,"2010-08-13 07:51:27, 2010-08-14 06:35:15, 2010..."
3534,4448,zzu6_r3DxBJuXcjnOYVdTw,"2011-05-24 01:35:13, 2012-01-01 23:44:33, 2012..."

## User-User Edge

In [7]:
ls1 = [x for x in new_user_df["user_id"]]
ls2 = [y for y in new_user_df["friends"]]
ls = []
for u, x in zip(ls1, ls2):
    if u != "#NAME?":
        x = [y.strip(" '") for y in x.strip("[]").split(",")]
        for data in x:
            if data != "":
                # print([u, data])
                ls.append([u, data])  # A pair of user_id and friends

In [8]:
freq_table = review_train_df.pivot_table(
    index="user_id", columns="business_id", values="text", aggfunc="count"
)

freq_table.fillna(0, inplace=True)
freq_table

business_id,--8IbOsAAxjKRoYsBFL-PA,-0__F9fnKt8uioCKztF5Ww,-0ltw8--HLuulPyOSspqAQ,-1XSzguS6XLN-V6MVZMg2A,-4x3pVUUsfWmKEilWKsOZQ,-6TttC-1-rf5gC0QHWrs_w,-7iiapq3BMer7eW-NRXd2w,-86Z04IBKxhEQ17rCOkn8g,-8B29WNRCyg4jViK4ChKlQ,-8luB5pJ7d9UOoiF7wikkw,...,zrUAjvPlH22dnvNtxRuiBg,zrWmHg7PNEE4URu2vLl67w,zrkvXc-pG-loBBGJMN5IiQ,zsi8oJBaY3UrMMmQm4DncA,ztcOE7NN0WdleNOCbje8ng,zurZgdE3W9jJnU6VAgTdSg,zvGNZF827KyzLupKiG4Xtw,zwe9H6Xxqb1_E09A20Ptgg,zzbZtgPYZS8sTIWQH6DwEw,zzu6_r3DxBJuXcjnOYVdTw
user_id,,,,,,,,,,,,,,,,,,,,,
---UgP94gokyCDuB5zUssA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
--XwFm4qERD6J5SX0JAsbg,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
--cPqjzKHqHKmGala65zwg,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
--vN7C-lXaBve7Sl02Y_9Q,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-0LGLx8LP5dq3zcGO4Bebw,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zy0el7c-IO4BvjxUgj-ZSw,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zy7HqigeNvAU0TpDra-H9g,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zzDtNDtESTyAXX3glz4MWQ,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zzgLgszu48af4NJULymzAA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zziWJMYwDjyVi7kJmgRUvg,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
set(freq_table.iloc[0].loc[lambda df: df.ne(0)].index)

{'GBTPC53ZrG1ZBY3DT8Mbcw',
 'hKr-RKMVpj3gRkSWcjg3Zw',
 'mV1UTSvEm-mhaPGFiIGhhQ',
 'mnq8JNUjIBwUoLBk-b2V9g',
 'zrUAjvPlH22dnvNtxRuiBg'}

In [10]:
def User2UserWeight(user1, user2, freq_table, eps=1e-4):
    numerator = 0
    user1_business = set(freq_table.loc[user1].loc[lambda df: df.ne(0)].index)
    user2_business = set(freq_table.loc[user2].loc[lambda df: df.ne(0)].index)
    for business in user1_business & user2_business:
        numerator += min(
            freq_table.loc[user1][business], freq_table.loc[user2][business]
        )
    numerator += eps
    denominator = len(user1_business & user2_business) + 1
    return round(numerator / denominator, 4)

In [ ]:
with open("User2User_edges.txt", "w") as f:
    for data in tqdm(ls):
        try:
            if data[0] in freq_table.index and data[1] in freq_table.index:
                f.write(str(data[0]))
                f.write(",")
                f.write(str(data[1]))
                f.write(",")
                f.write(str(User2UserWeight(data[0], data[1], freq_table)))
                f.write("\n")  # A pair of user_id and friends
        except:
            pass

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 330745/330745 [00:28<00:00, 11650.16it/s]

## User-Poi Edge

In [ ]:
import torch
from tqdm import tqdm
from transformers import AutoModelForSequenceClassification, AutoTokenizer

device = (
    "cuda"
    if torch.cuda.is_available()
    else ("mps" if torch.backends.mps.is_available() else "cpu")
)
print(device)

model = AutoModelForSequenceClassification.from_pretrained(
    "nihaldsouza1/yelp-rating-classification",
)

tokenizer = AutoTokenizer.from_pretrained(
    "nihaldsouza1/yelp-rating-classification",
    truncation=True,
    max_length=512,
)

mps

In [25]:
review_train_df["text"].values

array(["Cute interior and owner (?) gave us tour of upcoming patio/rooftop area which will be great on beautiful days like today. Cheese curds were very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. Wasn't too much cheese which I liked. Needed something else...pepper jelly maybe. Would like to see more menu options added such as salads w fun cheeses. Lots of beer and wine as well as limited cocktails. Next time I will try one of the draft wines.",
       'In a word... "OVERRATED!".  The food took forever to come out.  The burger was WAY overcooked (Especially when I ordered it Medium Rare) and the Seafood Jumbalaya was Decent.  Not worth the price.  There are better places to eat in the french quarter.  It was not horrible, but for everything that we had heard about this place, I would have expected much better.',
       "NEVER AGAIN. This is a so called restaurant that does nothing that a restaurant should other than prepare food, because the rest is done by the patron. Want water? Get up and go across the yard to get it. Want a drink, walk up a flight of stairs and pay cash. Want to sit in a dirty yard in dirty lawn chairs, enjoy yourself. The wait staff is mildy helpful in that they bring you your food after you go to the window and pay cash for it...kind of like New Orleans Hamburger and Seafood, but dirty and with live music (which is nice). It's a one in a lifetime experience for me...just once.",
       ..., 'Not 24hr!!!!',
       'Kyoto is closed for good. Some corporation bought it and the future of the location is unclear.',
       'Great food, even better margaritas!!! Best Mexican food on the west bank!!!'],
      dtype=object)

In [ ]:
tokenizer

<bound method PreTrainedTokenizerBase.truncate_sequences of RobertaTokenizerFast(name_or_path='nihaldsouza1/yelp-rating-classification', vocab_size=50265, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}, clean_up_tokenization_spaces=False),  added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50264: AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=False, special=True),
}>

In [34]:
model.to(device)

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-5): 6 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=5, bias=True)
  )
)

In [38]:
res = list(review_train_df["text"].values)

star = []
model.eval()
model.to(device)
with torch.no_grad():
    for i in tqdm(range(len(res))):
        inputs = res[i]
        inputs = tokenizer(inputs, return_tensors="pt", truncation=True)
        inputs.to(device)
        k = torch.argmax(model(**inputs).logits[0]).item() + 1
        star.append(k)

  1%|          | 1073/189573 [01:03<3:06:15, 16.87it/s]

KeyboardInterrupt:

In [ ]:
temp = review_train_df["stars"]
star = pd.Series(star)
temp.loc[temp.isnull()] = star.loc[temp.isnull()]
review_train_df["new_stars"] = (temp + star) / 2

158062   NaN
158063   NaN
158064   NaN
158065   NaN
158066   NaN
          ..
189568   NaN
189569   NaN
189570   NaN
189571   NaN
189572   NaN
Name: stars, Length: 31511, dtype: float64

In [58]:
review_train_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,compliment_count,count
0,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1.0,0.0,1.0,Cute interior and owner (?) gave us tour of up...,1.484427e+09,NaN,None
1,jC-fGfx-YLqxVBcyTAd4Pw,EBa-0-6AKoy6jziNexDJtg,W4ZEKkva9HpAdZG88juwyQ,3.0,0.0,0.0,0.0,"In a word... ""OVERRATED!"". The food took fore...",1.388285e+09,NaN,None
2,Ki90-hauSIfW_7sBuBBqfA,Z2cOL3n9V8NoguJ-uU_Nvw,j8JOZvfeHEfUWq3gEz6ABQ,2.0,2.0,3.0,0.0,NEVER AGAIN. This is a so called restaurant th...,1.402499e+09,NaN,None
3,fGYcFOHfQL4stYPdD3J47g,CgyCtH9CbLO7J_uO3cL7OA,PzhPMkaNYiKDTHoTG0r8rw,4.0,0.0,0.0,0.0,After 3 weeks of working in the area I finally...,1.474239e+09,NaN,None
4,zRIH5eDA2GbynjZPrk8dDg,07aVWNhBhpwqW3MdqoKDKQ,jLerIZFpe25jOUf722qzBA,3.0,1.0,0.0,1.0,My food only merited maybe two stars but I wil...,1.300625e+09,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...
189568,None,pmicanKB33RORORyuW-FRw,ujYhU3bX35BCVj1NUbSQpQ,NaN,NaN,NaN,NaN,Not a huge menu...some sandwiches and pastries...,1.372874e+09,0.0,None
189569,None,6mqnjHUgNEGtb9H5dxQZew,TcNZXteosegb1RO4O5hREw,NaN,NaN,NaN,NaN,Fried Oyster Poorboys on Monday and Wednesday!...,1.405354e+09,0.0,None
189570,None,S7bRCe31-pZNNivo9HmYeg,95tAFc8hVfzVr0uRJuDbaw,NaN,NaN,NaN,NaN,Not 24hr!!!!,1.429599e+09,0.0,None
189571,None,S7bRCe31-pZNNivo9HmYeg,0ZeGH15LV98FuijA1XrWoA,NaN,NaN,NaN,NaN,Kyoto is closed for good. Some corporation bou...,1.476826e+09,0.0,None
189572,None,ZoTe31b0sQ2EH-ucMuxyvw,mbKGY9CcbjSvy3Iyumeg3Q,NaN,NaN,NaN,NaN,"Great food, even better margaritas!!! Best Mex...",1.460166e+09,0.0,None

In [ ]:
def User2PoiWeight(user_id, business_id, freq_table):
    star = review_train_df.loc[
        (review_train_df["user_id"] == user_id)
        & (review_train_df["business_id"] == business_id)
    ]["new_stars"]
    return star

In [ ]:
review_train_df.pivot_table(
    index="user_id",
    columns="business_id",
    values="new_stars",
    aggfunc="count",
    fill_value=0,
)
with open("User2Poi_edges.txt", "w") as f:
    for user_id in tqdm(freq_table.index):
        for business_id in freq_table.columns:
            if freq_table.loc[user_id][business_id] >= 1:
                f.write(str(user_id))
                f.write(",")
                f.write(str(business_id))
                f.write(",")
                f.write(str(User2PoiWeight(user_id, business_id, freq_table)))
                f.write("\n")

## Poi-Poi Edge

In [8]:
from datetime import datetime

review_train_df["date2"] = [datetime.fromtimestamp(x) for x in review_train_df["date"]]
review_train_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,compliment_count,count,date2
0,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1.0,0.0,1.0,Cute interior and owner (?) gave us tour of up...,1.484427e+09,NaN,None,2017-01-15 04:54:15
1,jC-fGfx-YLqxVBcyTAd4Pw,EBa-0-6AKoy6jziNexDJtg,W4ZEKkva9HpAdZG88juwyQ,3.0,0.0,0.0,0.0,"In a word... ""OVERRATED!"". The food took fore...",1.388285e+09,NaN,None,2013-12-29 10:37:42
2,Ki90-hauSIfW_7sBuBBqfA,Z2cOL3n9V8NoguJ-uU_Nvw,j8JOZvfeHEfUWq3gEz6ABQ,2.0,2.0,3.0,0.0,NEVER AGAIN. This is a so called restaurant th...,1.402499e+09,NaN,None,2014-06-11 22:55:14
3,fGYcFOHfQL4stYPdD3J47g,CgyCtH9CbLO7J_uO3cL7OA,PzhPMkaNYiKDTHoTG0r8rw,4.0,0.0,0.0,0.0,After 3 weeks of working in the area I finally...,1.474239e+09,NaN,None,2016-09-19 06:43:18
4,zRIH5eDA2GbynjZPrk8dDg,07aVWNhBhpwqW3MdqoKDKQ,jLerIZFpe25jOUf722qzBA,3.0,1.0,0.0,1.0,My food only merited maybe two stars but I wil...,1.300625e+09,NaN,None,2011-03-20 20:44:20
...,...,...,...,...,...,...,...,...,...,...,...,...
189568,None,pmicanKB33RORORyuW-FRw,ujYhU3bX35BCVj1NUbSQpQ,NaN,NaN,NaN,NaN,Not a huge menu...some sandwiches and pastries...,1.372874e+09,0.0,None,2013-07-04 01:47:41
189569,None,6mqnjHUgNEGtb9H5dxQZew,TcNZXteosegb1RO4O5hREw,NaN,NaN,NaN,NaN,Fried Oyster Poorboys on Monday and Wednesday!...,1.405354e+09,0.0,None,2014-07-15 00:08:11
189570,None,S7bRCe31-pZNNivo9HmYeg,95tAFc8hVfzVr0uRJuDbaw,NaN,NaN,NaN,NaN,Not 24hr!!!!,1.429599e+09,0.0,None,2015-04-21 14:53:47
189571,None,S7bRCe31-pZNNivo9HmYeg,0ZeGH15LV98FuijA1XrWoA,NaN,NaN,NaN,NaN,Kyoto is closed for good. Some corporation bou...,1.476826e+09,0.0,None,2016-10-19 05:19:35
189572,None,ZoTe31b0sQ2EH-ucMuxyvw,mbKGY9CcbjSvy3Iyumeg3Q,NaN,NaN,NaN,NaN,"Great food, even better margaritas!!! Best Mex...",1.460166e+09,0.0,None,2016-04-09 09:42:58

In [9]:
time_table = review_train_df.pivot_table(
    index="user_id",
    columns="business_id",
    values="date2",
)
time_table

business_id,--8IbOsAAxjKRoYsBFL-PA,-0__F9fnKt8uioCKztF5Ww,-0ltw8--HLuulPyOSspqAQ,-1XSzguS6XLN-V6MVZMg2A,-4x3pVUUsfWmKEilWKsOZQ,-6TttC-1-rf5gC0QHWrs_w,-7iiapq3BMer7eW-NRXd2w,-86Z04IBKxhEQ17rCOkn8g,-8B29WNRCyg4jViK4ChKlQ,-8luB5pJ7d9UOoiF7wikkw,...,zrUAjvPlH22dnvNtxRuiBg,zrWmHg7PNEE4URu2vLl67w,zrkvXc-pG-loBBGJMN5IiQ,zsi8oJBaY3UrMMmQm4DncA,ztcOE7NN0WdleNOCbje8ng,zurZgdE3W9jJnU6VAgTdSg,zvGNZF827KyzLupKiG4Xtw,zwe9H6Xxqb1_E09A20Ptgg,zzbZtgPYZS8sTIWQH6DwEw,zzu6_r3DxBJuXcjnOYVdTw
user_id,,,,,,,,,,,,,,,,,,,,,
---UgP94gokyCDuB5zUssA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,2014-11-03 06:00:08,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
--XwFm4qERD6J5SX0JAsbg,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
--cPqjzKHqHKmGala65zwg,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
--vN7C-lXaBve7Sl02Y_9Q,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
-0LGLx8LP5dq3zcGO4Bebw,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zy0el7c-IO4BvjxUgj-ZSw,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
zy7HqigeNvAU0TpDra-H9g,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
zzDtNDtESTyAXX3glz4MWQ,NaT,NaT,NaT,NaT,2016-09-24 08:46:03,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
zzgLgszu48af4NJULymzAA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
zziWJMYwDjyVi7kJmgRUvg,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT

In [11]:
t = time_table.loc["zzDtNDtESTyAXX3glz4MWQ"]["-4x3pVUUsfWmKEilWKsOZQ"]
t

Timestamp('2016-09-24 08:46:03')

In [12]:
# Check which user has visited the specified business
time_table["-4x3pVUUsfWmKEilWKsOZQ"].sort_values().loc[lambda df: df.notnull()]

user_id
Roz6yC22LRB2wFJC6I9ERg   2014-04-11 09:58:48.000
qGIHVzXZvSoU6PfVFfOWqA   2014-05-01 07:25:10.000
9Nx0VL4f_8K6V6yfFLue1Q   2014-06-06 23:06:45.000
zn2RHz7IP4uM-Gsf5c1FHg   2014-07-06 09:59:41.000
sTKe0hIMr5_yV01jOWweSg   2014-07-31 09:59:05.000
H1GwyEuTXi-3nLk082wfHA   2014-08-13 10:59:26.000
2hTVUUriSLT6hWK8VY9WHg   2014-08-21 01:10:51.000
ZdODEy4O0-nPdPKwkdQkdw   2014-11-18 05:14:29.000
t7Z2hdnOE3FQeuu56eOxiA   2015-01-26 21:31:07.000
rL2hC27iA1AB9RvdLLbkNA   2015-02-10 00:41:55.000
CEAez8zEPRtntTjqfZ39NA   2015-03-02 01:36:04.000
CjwYS6PtNDlrLnHErQAgMQ   2015-03-02 02:56:09.000
ddvl_jow_K51vy2jM4oLxQ   2015-03-13 05:33:27.000
-OEWEH1WgWA3Nh-_6E3HMg   2015-04-16 04:35:59.000
02hpwTDFZVbufoc-x8W5zg   2015-05-03 10:07:52.000
1HM81n6n4iPIFU5d2Lokhw   2015-05-09 00:09:09.000
1-r671PdVDRV2zq1sEC9Gw   2015-05-26 06:42:50.000
q4LmkpMygPZqJkgWw-eD8w   2015-05-30 06:13:41.000
DB6zT8ouRNEoJ-kZlp32VA   2015-06-21 05:57:26.000
LuzOVxV_MtucPqwrNUZCUQ   2015-06-26 08:46:33.000
ShLvbrlY9qlJOwhkRINYOQ   2015-08-13 10:42:00.000
BVwZaapCwqZbIqBu2-9DWQ   2015-09-08 00:53:56.000
6Dsb-2P6Mm8BAdqGc7VIDg   2015-10-04 11:39:39.000
GxnQ6ss4O2lPQZXc4CGcJQ   2015-11-30 09:16:23.000
OAXKmnJgiboyTUkXwG9wsw   2015-12-14 00:46:54.000
CfX4sTIFFNaRchNswqhVfg   2016-01-15 10:24:09.000
skdAsWlekOcaA8WvAyYztQ   2016-04-04 21:34:43.000
usqHGWBX_cj3Q-moOjusrw   2016-04-24 12:03:47.000
forT0gYJlY7gIc7cFeho6w   2016-05-09 03:39:58.000
JvF4NULGespxybMObL9aig   2016-05-11 00:43:03.000
fJM_1YrTqlVPjgq2_ObDOA   2016-07-05 10:00:41.500
zzDtNDtESTyAXX3glz4MWQ   2016-09-24 08:46:03.000
ev947pHN53-GanH18JFn4A   2017-03-29 04:54:29.000
Name: -4x3pVUUsfWmKEilWKsOZQ, dtype: datetime64[ns]

In [13]:
# time_table["-4x3pVUUsfWmKEilWKsOZQ"].sort_values().loc[lambda df: df.notnull()].index
time_table.loc["Roz6yC22LRB2wFJC6I9ERg"].sort_values().loc[lambda df: df.notnull()]

business_id
M-6AXSgmDMYcWsF442mzzA   2011-11-17 09:25:18.000
ezb90IvaQ4sKojatZC80BA   2012-04-28 00:28:22.000
8QPeBH0APzUlokwD7S5G6Q   2012-05-09 09:43:29.000
3db1R99-mdSvx3QwryJSNQ   2012-05-15 05:15:39.000
_NfEP6cuFSz7bd-7OtiJ-Q   2013-08-12 03:59:30.000
b5EFmhN5S4DDlpxkku8VBw   2014-03-26 06:17:19.000
-4x3pVUUsfWmKEilWKsOZQ   2014-04-11 09:58:48.000
i9ahyW_GpP1nrMomY5BoFQ   2014-07-26 03:40:15.000
_SjdrpSZdiXVSwaJR5T9jw   2014-09-25 09:06:29.000
WZ5IxAi-hTRLrG1nRmyhVg   2014-11-15 03:12:26.000
KtiZ7-oI4n_yNazrZUnumQ   2015-01-04 08:27:34.000
QQng-ifjEZhI1Vb9j0Hb4A   2015-02-08 04:01:12.500
LYd7px5BfCrGeNLHyaDW6w   2015-06-19 04:04:45.500
CY23YgKIhIdFkoVLp7Vhhg   2015-08-16 01:39:40.000
uvQQlr5ye4ReQTxuyB7kCA   2015-11-12 07:38:53.000
LqQOn3EFOSY3eWZjjgv_eQ   2015-12-09 09:26:25.000
3euS__1BAL3ETiIuecS6ZQ   2016-05-25 00:30:51.000
Name: Roz6yC22LRB2wFJC6I9ERg, dtype: datetime64[ns]

In [14]:
t

Timestamp('2016-09-24 08:46:03')

In [15]:
time_table.loc["Roz6yC22LRB2wFJC6I9ERg"].sort_values().loc[lambda df: df.notnull()] > t

business_id
M-6AXSgmDMYcWsF442mzzA    False
ezb90IvaQ4sKojatZC80BA    False
8QPeBH0APzUlokwD7S5G6Q    False
3db1R99-mdSvx3QwryJSNQ    False
_NfEP6cuFSz7bd-7OtiJ-Q    False
b5EFmhN5S4DDlpxkku8VBw    False
-4x3pVUUsfWmKEilWKsOZQ    False
i9ahyW_GpP1nrMomY5BoFQ    False
_SjdrpSZdiXVSwaJR5T9jw    False
WZ5IxAi-hTRLrG1nRmyhVg    False
KtiZ7-oI4n_yNazrZUnumQ    False
QQng-ifjEZhI1Vb9j0Hb4A    False
LYd7px5BfCrGeNLHyaDW6w    False
CY23YgKIhIdFkoVLp7Vhhg    False
uvQQlr5ye4ReQTxuyB7kCA    False
LqQOn3EFOSY3eWZjjgv_eQ    False
3euS__1BAL3ETiIuecS6ZQ    False
Name: Roz6yC22LRB2wFJC6I9ERg, dtype: bool

In [16]:
time_table.columns

Index(['--8IbOsAAxjKRoYsBFL-PA', '-0__F9fnKt8uioCKztF5Ww',
       '-0ltw8--HLuulPyOSspqAQ', '-1XSzguS6XLN-V6MVZMg2A',
       '-4x3pVUUsfWmKEilWKsOZQ', '-6TttC-1-rf5gC0QHWrs_w',
       '-7iiapq3BMer7eW-NRXd2w', '-86Z04IBKxhEQ17rCOkn8g',
       '-8B29WNRCyg4jViK4ChKlQ', '-8luB5pJ7d9UOoiF7wikkw',
       ...
       'zrUAjvPlH22dnvNtxRuiBg', 'zrWmHg7PNEE4URu2vLl67w',
       'zrkvXc-pG-loBBGJMN5IiQ', 'zsi8oJBaY3UrMMmQm4DncA',
       'ztcOE7NN0WdleNOCbje8ng', 'zurZgdE3W9jJnU6VAgTdSg',
       'zvGNZF827KyzLupKiG4Xtw', 'zwe9H6Xxqb1_E09A20Ptgg',
       'zzbZtgPYZS8sTIWQH6DwEw', 'zzu6_r3DxBJuXcjnOYVdTw'],
      dtype='object', name='business_id', length=3535)

In [17]:
# Generate edges map from 1 PoI to another PoI
Poi2Poi = {}
for business in tqdm(
    time_table.columns,
):
    business_record = (
        time_table[business].sort_values().loc[lambda df: df.notnull()]
    )  # list of users
    after_visit = []
    for user in tqdm(business_record.index, leave=False):
        timeStamp = business_record.loc[user]
        # user trajectory
        user_trajectory = (
            time_table.loc[user].sort_values().loc[lambda df: df.notnull()]
        )

        user_trajectory = user_trajectory.loc[lambda df: df > timeStamp].index
        if len(user_trajectory) > 0:
            after_visit.append(user_trajectory[0])
    after_visit = list(set(after_visit))
    Poi2Poi[business] = (
        after_visit  # a list of PoI that are visited after visiting the current PoI
    )

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3535/3535 [01:21<00:00, 43.48it/s]

business -> [business1, business2, business3, ...]

In [19]:
from geopy.distance import geodesic

pd.set_option("display.precision", 10)

In [20]:
new_business_df["latitude"]

0       29.8754822266
1       29.9333877563
2       29.8753202000
3       29.9767620000
4       29.9486236188
            ...
3530    30.0024000000
3531    29.9559253000
3532    30.0211394706
3533    30.0130808120
3534    29.9547095000
Name: latitude, Length: 3535, dtype: float64

In [21]:
new_business_df[["latitude", "longitude"]].value_counts()

latitude       longitude
29.9595769000  -90.0770127000    9
29.9693909000  -90.0521636000    8
29.9219677000  -90.1073935000    7
29.9510658000  -90.0715323000    7
29.9682679000  -90.0326531000    5
                                ..
29.9475550000  -90.1304900000    1
29.9475570000  -90.1133610000    1
29.9475628172  -90.0633108616    1
29.9475671000  -90.0651152000    1
30.0515811000  -89.9789026000    1
Name: count, Length: 3370, dtype: int64

In [22]:
# new_business_df[new_business_df["latitude"] == 29.8754822266]
new_business_df[["latitude", "longitude"]].value_counts().loc[lambda df: df > 1]

latitude    longitude
29.9595769  -90.0770127    9
29.9693909  -90.0521636    8
29.9219677  -90.1073935    7
29.9510658  -90.0715323    7
29.9682679  -90.0326531    5
                          ..
29.9226351  -90.0911594    2
29.9215527  -90.1172213    2
30.0051731  -90.1052748    2
29.9592236  -90.0604606    2
29.9660415  -90.0511120    2
Name: count, Length: 120, dtype: int64

In [52]:
Poi2Poi_dis = {}
negative_exponent = -3

for business, after_visit in tqdm(Poi2Poi.items()):
    for poi in after_visit:
        business_loc = new_business_df.loc[new_business_df["business_id"] == business][
            ["latitude", "longitude"]
        ].values[0]
        poi_loc = new_business_df.loc[new_business_df["business_id"] == poi][
            ["latitude", "longitude"]
        ].values[0]
        Poi2Poi_dis[(business, poi)] = (
            geodesic(business_loc, poi_loc).meters + 1e-2
        ) ** negative_exponent
    Poi2Poi_dis[(business,)] = sum(
        [Poi2Poi_dis[(business, poi)] for poi in after_visit]
    )

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3535/3535 [01:16<00:00, 46.12it/s]

In [ ]:
Poi2Poi_weight = {}
for business1 in tqdm(time_table.columns, position=0):
    for business2 in tqdm(Poi2Poi[business1], position=1):
        tmp = 0  # sum of weight
        for users in time_table.loc[lambda df: df[business1].notnull()].index:
            user_trajectory = (
                time_table.loc[users].sort_values().loc[lambda df: df.notnull()]
            )
            for idx, poi in enumerate(user_trajectory.index):
                if (idx + 1) < len(user_trajectory):
                    if (
                        user_trajectory.index[idx] == business1
                        and user_trajectory.index[idx + 1] == business2
                    ):
                        tmp += (
                            Poi2Poi_dis[(business1, business2)]
                            / Poi2Poi_dis[(business1,)]
                        )
        Poi2Poi_weight[(business1, business2)] = tmp

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 7/7 [00:00<00:00, 109.39it/s]
  0%|          | 0/3535 [00:00<?, ?it/s]

In [54]:
Poi2Poi_weight

{('--8IbOsAAxjKRoYsBFL-PA', 'HDnaNdHEZpQMYXo-ZHHG9g'): 0.032066249758896825,
 ('--8IbOsAAxjKRoYsBFL-PA', 'MiTuey9Pdc2haG9KQgmU7Q'): 0.025966465489519804,
 ('--8IbOsAAxjKRoYsBFL-PA', 'joxy9N8aJv3_6h0aaYuTzA'): 0.016874026807451488,
 ('--8IbOsAAxjKRoYsBFL-PA', 'ORVWMFwF5qTWy9Cbahf0Pg'): 0.013295956263152891,
 ('--8IbOsAAxjKRoYsBFL-PA', '9ZoWmU5Y_vyjsfyJhikXLA'): 0.0030790423678784757,
 ('--8IbOsAAxjKRoYsBFL-PA', '_QYncK8LjXswVYZ_jv_q7A'): 0.902856008149813,
 ('--8IbOsAAxjKRoYsBFL-PA', '3NgkGlI1QrEc-5g8zvVpKQ'): 0.005862251163287358}

In [48]:
for k, v in Poi2Poi_dis.items():
    bus1, bus2 = k
    print()

ValueError: not enough values to unpack (expected 2, got 1)

In [49]:
Poi2Poi_dis[("--8IbOsAAxjKRoYsBFL-PA", "HDnaNdHEZpQMYXo-ZHHG9g")]

1.5971832972126425e-26

In [51]:
new_business_df.loc[new_business_df["business_id"] == "--8IbOsAAxjKRoYsBFL-PA"][
    ["latitude", "longitude"]
]

        latitude  longitude
1390  30.0063408 -90.074523

In [ ]:
review_train_df[]

In [56]:
with open("Poi2Poi_edges.txt", "w") as f:
    for k, v in tqdm(Poi2Poi_weight.items()):
        f.write(str(k[0]))
        f.write(",")
        f.write(str(k[1]))
        f.write(",")
        f.write(str(v))
        f.write("\n")

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 7/7 [00:00<00:00, 12682.56it/s]

## node_type_ID.txt

In [ ]:
# The node_type_ID.txt format is as follows:
# node_id   node_type
# 0         U
# 1         U
# 2         P
# 3         P

## edge_type_ID.txt
with open("edge_type_ID.txt", "w") as f:
    for user_id in review_train_df["user_id"].unique():
        f.write(f"{user_id}\tU\n")
    for poi_id in review_train_df["business_id"].unique():
        f.write(f"{poi_id}\tP\n")

## Concatenate all edge weights files

In [ ]:
## edge_ID.txt
# Read all edges from the file (Poi2Poi_edges.txt, User2Poi_edges.txt, User2User_edges.txt) and write them to the edge_ID.txt file
with open("edge_ID.txt", "w") as f:
    with open("Poi2Poi_edges.txt", "r") as f1:
        for line in f1:
            f.write(line)
    with open("User2Poi_edges.txt", "r") as f2:
        for line in f2:
            f.write(line)
    with open("User2User_edges.txt", "r") as f3:
        for line in f3:
            f.write(line)